create table public."Repositories" (
  "ID" integer generated by default as identity not null,
  "Name" text not null,
  "Link" text not null,
  "Details" text null,
  "DisplayOrder" timestamp with time zone null,
  "EstimatedTime" numeric null,
  "CommitCount" smallint null,
  "Details_ja" text null,
  "Languages" text[] null,
  constraint Repositories_pkey primary key ("ID")
) TABLESPACE pg_default;