-- =============================================================================
-- Database Configuration
-- =============================================================================
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SELECT pg_catalog.set_config('search_path', '', false);

SET default_tablespace = '';
SET default_table_access_method = heap;

-- =============================================================================
-- Extensions
-- =============================================================================
CREATE EXTENSION IF NOT EXISTS "pg_cron"            WITH SCHEMA pg_catalog;
CREATE EXTENSION IF NOT EXISTS "pg_net"             WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "pgcrypto"           WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "supabase_vault"     WITH SCHEMA vault;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp"          WITH SCHEMA extensions;

COMMENT ON SCHEMA public IS 'standard public schema';

-- =============================================================================
-- Functions
-- =============================================================================
CREATE OR REPLACE FUNCTION public.rls_auto_enable()
RETURNS event_trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog
AS $$
DECLARE
    cmd record;
BEGIN
    FOR cmd IN
        SELECT *
        FROM pg_event_trigger_ddl_commands()
        WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
          AND object_type IN ('table', 'partitioned table')
    LOOP
        IF cmd.schema_name = 'public' THEN
            BEGIN
                EXECUTE format(
                    'ALTER TABLE IF EXISTS %s ENABLE ROW LEVEL SECURITY',
                    cmd.object_identity
                );

                RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
            EXCEPTION
                WHEN OTHERS THEN
                    RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
            END;
        END IF;
    END LOOP;
END;
$$;

ALTER FUNCTION public.rls_auto_enable() OWNER TO postgres;
-- =============================================================================
-- Tables
-- =============================================================================
CREATE TABLE IF NOT EXISTS public."Repositories" (
    "ID"              integer NOT NULL,
    "Name"            text NOT NULL,
    "Link"            text NOT NULL,
    "Details"         text,
    "DisplayOrder"    timestamptz,
    "EstimatedTime"   numeric,
    "CommitCount"     smallint,
    "Details_ja"      text,
    "Languages"       text[]
);

ALTER TABLE public."Repositories"
    OWNER TO postgres;

ALTER TABLE public."Repositories"
    ALTER COLUMN "ID"
    ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public."Repositories_id_seq"
        START WITH 1
        INCREMENT BY 1
        CACHE 1
    );

ALTER TABLE ONLY public."Repositories"
    ADD CONSTRAINT "Repositories_pkey"
    PRIMARY KEY ("ID");

-- =============================================================================
-- Row Level Security
-- =============================================================================
ALTER TABLE public."Repositories"
    ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users"
ON public."Repositories"
FOR SELECT
USING (true);

-- =============================================================================
-- Publications
-- =============================================================================
ALTER PUBLICATION supabase_realtime
    OWNER TO postgres;

-- =============================================================================
-- Permissions
-- =============================================================================
GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;

REVOKE ALL ON FUNCTION public.rls_auto_enable() FROM PUBLIC;
GRANT ALL ON FUNCTION public.rls_auto_enable() TO service_role;

GRANT ALL ON TABLE public."Repositories" TO anon;
GRANT ALL ON TABLE public."Repositories" TO authenticated;
GRANT ALL ON TABLE public."Repositories" TO service_role;

GRANT ALL ON SEQUENCE public."Repositories_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."Repositories_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."Repositories_id_seq" TO service_role;

-- =============================================================================
-- Default Privileges
-- =============================================================================
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
    GRANT ALL ON TABLES TO postgres, anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
    GRANT ALL ON FUNCTIONS TO postgres, anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
    GRANT ALL ON SEQUENCES TO postgres, anon, authenticated, service_role;